### ISSUE TITLE
Main branch broken/inconsistent by commit 5af328e – [FIX] gtpsa api change: desc initalisation and test

### ISSUE THREAD

**Issue by jbengtsson** [hz-b/gtpsa-cpp#5]
While thor-scsi-lib can be built & validated with commit 20bce44 – this is no longer the case for commit 5af328e:

In file included from /Users/johan/git/thor-scsi-lib_jb/src/gtpsa/c++/gtpsa/mad/tpsa_wrapper.cc:1:
In file included from /Users/johan/git/thor-scsi-lib_jb/src/gtpsa/c++/gtpsa/mad/tpsa_wrapper.hpp:39:
In file included from /Users/johan/git/thor-scsi-lib_jb/src/gtpsa/c++/gtpsa/mad/wrapper.tpp:38:
/Users/johan/git/thor-scsi-lib_jb/src/gtpsa/c++/gtpsa/desc.hpp:52:2: warning: "gtpsa::desc: not deleting underlying gtpsa desc_t object. see comment in <gtpsa/desc.hpp>" [-W#warnings]
#warning "gtpsa::desc: not deleting underlying gtpsa desc_t object. see comment in <gtpsa/desc.hpp>"
 ^
In file included from /Users/johan/git/thor-scsi-lib_jb/src/gtpsa/c++/gtpsa/desc.cc:1:
/Users/johan/git/thor-scsi-lib_jb/src/gtpsa/c++/gtpsa/desc.hpp:52:2: warning: "gtpsa::desc: not deleting underlying gtpsa desc_t object. see comment in <gtpsa/desc.hpp>" [-W#warnings]
#warning "gtpsa::desc: not deleting underlying gtpsa desc_t object. see comment in <gtpsa/desc.hpp>"
 ^
/Users/johan/git/thor-scsi-lib_jb/src/gtpsa/c++/gtpsa/desc.hpp:112:40: error: no matching function for call to 'mad_desc_newvpo'
            : dm( std::make_unique<desc_mgr>( mad_desc_newvpo(nv, mo, np, po, no) ) )
                                              ^~~~~~~~~~~~~~~
/Users/johan/git/thor-scsi-lib_jb/src/gtpsa/mad-ng/src/mad_desc.h:59:15: note: candidate function not viable: requires 4 arguments, but 5 were provided
const desc_t* mad_desc_newvpo(int nv, int np, const ord_t no[], ord_t po_);
              ^
...

**Comment by PierreSchnizer** [comment]
name index branch now renamed to main
Main build verified with CI now.
Please start with a fresh install
